User.create(username: "Doctor", password: "Phil")
User.create(username: "Chuck", password: "Norris")
User.create(username: "Philip", password: "Roth")
User.create(username: "Tinker", password: "Tailor")
user = User.create(username: "Chris", password: "Kay")

user.experiences << Experience.create(name: "Drive a race car")
user.experiences << Experience.create(name: "Buy a house", user_id: user.id)
user.experiences << Experience.create(name: "Attend Carnival in Brazil")
user.experiences << Experience.create(name: "Learn to surf")
user.experiences << Experience.create(name: "Backpack through Europe")
user.experiences << Experience.create(name: "Learn programming")
user.experiences << Experience.create(name: "Pay off all my debts")
user.experiences << Experience.create(name: "Go on an African safari")
user.experiences << Experience.create(name: "Start a business")
user.experiences << Experience.create(name: "Run a marathon")

user.destinations << Destination.create(city: "Angkor Wat", country: "Cambodia")
user.destinations << Destination.create(city: "Athens", country: "Greece")
user.destinations << Destination.create(city: "New York", country: "USA")
user.destinations << Destination.create(city: "Moscow", country: "Russia")
user.destinations << Destination.create(city: "London", country: "England")
user.destinations << Destination.create(city: "Paris", country: "France")
user.destinations << Destination.create(city: "Sydney", country: "Australia")
user.destinations << Destination.create(city: "Gobeklitepe", country: "Turkey")
user.destinations << Destination.create(city: "Bangkok", country: "Thailand")
user.destinations << Destination.create(city: "Tokyo", country: "Japan")