User.create(username: "Todd", password: "Gaston")
User.create(username: "Doctor", password: "Phil")
User.create(username: "Chuck", password: "Norris")
User.create(username: "Philip", password: "Roth")
User.create(username: "Tinker", password: "Tailor")