User.create(username: "Doctor", password: "Phil")
User.create(username: "Chuck", password: "Norris")
User.create(username: "Philip", password: "Roth")
User.create(username: "Tinker", password: "Tailor")
user = User.create(username: "chris", password: "kay")

user.destinations << Destination.create(city: "Angkor Wat", country: "Cambodia")
user.destinations << Destination.create(city: "Athens", country: "Greece")
user.destinations << Destination.create(city: "New York", country: "USA")
user.destinations << Destination.create(city: "Moscow", country: "Russia")
user.destinations << Destination.create(city: "London", country: "England")
user.destinations << Destination.create(city: "Paris", country: "France")
user.destinations << Destination.create(city: "Sydney", country: "Australia")
user.destinations << Destination.create(city: "Gobeklitepe", country: "Turkey")
user.destinations << Destination.create(city: "Bangkok", country: "Thailand")
user.destinations << Destination.create(city: "Tokyo", country: "Japan")